### PR TITLE
Minor UI changes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Javran** [comment]
thanks for the PR, need to take a closer look but here are few things:

- the background color seems to be hard coded, does it work for all themes? (excluding lighter ones as they are considered legacy)
- does the screenshot icon give you confusion on what it does? it's my intention to have no labels for these icons as this adds i18n efforts. plus in main app a screenshot button underneath game screen which uses exactly the same icon so I think it's easy for user to figure out that it would do.

**Comment by ghost** [comment]
The color is white text over a dark gray background, it definitively is hard coded but white over black would remain no matter what theme is changed (only for the content, the header will still change according to the theme)

Here's an example

Exported image before this changes (transparent background for content, which gets lost if image is attached in a background of similar color to the font color)


Image with these changes (background color and font color always contrast)


Using a different theme (only header will change to the theme, but the contents will remain with the white over gray)


The idea was just to avoid the issues of having a transparent background

The export image button is confusing at first, once I knew what to do it wasn't much of an issue but I thought it would be better if I knew what a button did without having to click it.

Yes, it might add a bit more to translate but it's just a single sentence and I thought it would be fine considering that words like "Fleet", "World" and "Auto" did not seem to be translated either.

You're right about being the same icon as the screenshot icon in the viewer, I did not notice until now

**Comment by Javran** [comment]
I see, it all sounds reasonable to me, how about this:

- we make a tooltip around screenshot button just like one in main app does, this should keep UI concise
- then about themes, I think there's a selector in poi that gives you current theme (not sure where is the selector located, probably `views/utils/selectors`, but alternatively you can use `getStore().config.poi.theme`) so we can create matching colors for every theme

if this all sounds good, feel free to go ahead and do it. I can also do this too, but if so expect it to come few days later, as I'm sick right now and not really in a good shape when it comes to coding...

**Comment by ghost** [comment]
All right, I made a couple changes, first is adding a tooltip with "Export Image" when hovering over the button, the text is no longer there.

As for the background, I started testing things with other themes and noticed something, the panel is already being themed properly with the unmodified code, but the problem is that themes seem to use really transparent white backgrounds in the panels (since the background is already gray-ish in poi, there's no need for the panels to have solid colors), I tried to add a class to the panel to make it theme like a different element from the theme, but it seems like all themes have transparent things here and there, so applying button styling (just as an example) might be fine for themes that have buttons with solid colors, but others do have them transparent which goes back to the original issue.

I couldn't find any element that was consistently solid-colored across all themes, for now I just left the gray background but made it a bit more transparent (but it's still visible while exporting images)

**Comment by Javran** [comment]
thanks! that's some decent work!

**Pull request merged**
